
export const NOW_PLAYING = {
  FETCH_START: "NOW_PLAYING.FETCH_START",
  FETCH_SUCCESS: "NOW_PLAYING.FETCH_SUCCESS",
  FETCH_FAIL: "NOW_PLAYING.FETCH_FAIL",
};

export const LATEST = {
  FETCH_START: "LATEST.FETCH_START",
  FETCH_SUCCESS: "LATEST.FETCH_SUCCESS",
  FETCH_FAIL: "LATEST.FETCH_FAIL",
};

export const UPCOMING = {
  FETCH_START: "UPCOMING.FETCH_START",
  FETCH_SUCCESS: "UPCOMING.FETCH_SUCCESS",
  FETCH_FAIL: "UPCOMING.FETCH_FAIL",
};

export const MOVIE_DETAILS = {
  FETCH_START: "MOVIE_DETAILS.FETCH_START",
  FETCH_SUCCESS: "MOVIE_DETAILS.FETCH_SUCCESS",
  FETCH_FAIL: "MOVIE_DETAILS.FETCH_FAIL",
};
